<template>
    <div class="flex flex-col  max-w-[1000px] grow mx-auto text-[#545353] font-medium gap-3">
        <h1 class="text-[#545353] text-[28px] font-bold">XML Sitemap</h1>
        <p class="text-[#545353] font-medium mt-[10px]">Generated by <a href="https://yoa.st/1y5" target="_blank" class="text-[#da3114]"> Yoast SEO</a>, this is an XML Sitemap, meant for consumption by search engines.</p>
        <p class="text-[#545353] font-medium ">You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" class="text-[#da3114]">sitemaps.org</a></p>
        <p>This XML Sitemap contains 145 URLs.</p>

        <table class="table-fixed">
            <thead class="border-gray-700 border-b-[2px]">
                <tr class="flex flex-row w-full ">
                    <th class="flex w-[70%]">URL</th><th class="flex w-[30%]">Last Mod.</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="i in counter.Data_link_Sitemap" class="flex flex-row w-full ">
                    <td class="flex w-[70%] cursor-pointer hover:underline text-[16px] font-medium text-gray-800"><a :herf="i.Link_URL" target="blank_">{{ i.Link_URL }}</a></td><td class="flex w-[30%] text-[15px] font-medium text-gray-800">{{ i.Thoi_gian }}</td>
                </tr>
            </tbody>
            </table>
    </div>
</template>

<script>
  import { useCounterStore } from '@/stores/counter';
  import axios from 'axios';
  import VueCookies from 'vue-cookies'


  export default {

  setup() {
      const counter = useCounterStore();
      return {counter}
  },
  mounted:function(){
    this.counter.Data_link_Sitemap_all();
    document.title = 'XML Sitemap';
  },
  components: {
  }
  }
</script>